#!/bin/bash
apt-get update && sudo apt-get upgrade
echo -e "\nDo you want to install VNC?"
echo -e "\n1. Yes, Install VNC (Graphical)"
echo "2. Yes,Install VNC (Non-Graphical)"
echo "3. No, Do not install VNC"
while :
do
  read INPUT_STRING
  case $INPUT_STRING in
	1)
		sudo apt-get update -y
		sudo apt-get install xfce4 xfce4-goodies tightvncserver -y --allow-unauthenticated
		vncserver
		vncserver -kill :1
		mv ~/.vnc/xstartup ~/.vnc/xstartup.bak
		echo "#!/bin/bash
		xrdb $HOME/.Xresources
		startxfce4 &" >> ~/.vnc/xstartup
		sudo chmod +x ~/.vnc/xstartup
		echo "#!/bin/bash
		PATH="$PATH:/usr/bin/"
		export USER="user"
		DISPLAY="1"
		DEPTH="16"
		GEOMETRY="1024x768"
		OPTIONS="-depth ${DEPTH} -geometry ${GEOMETRY} :${DISPLAY} -localhost"
		. /lib/lsb/init-functions" >> /etc/init.d/vncserver
		sudo chmod +x /etc/init.d/vncserver
		rm /etc/hostname
		echo "Parrot OS" >> /etc/hostname
		vncserver
		su
		clear
		echo "VNC SEVER STARTED ON PORT :1"
		echo "Connect it!!! Example :- ipaddress:1 in VNC Viewer"
		break
		;;
	2)	
		sudo apt-get install -y tightvncserver --allow-unauthenticated
		vncserver
		netstat -plant
		vncserver -kill :1
		vncserver
		rm /etc/hostname
		echo "Parrot OS" >> /etc/hostname
		vncserver
		su
		clear
		echo "VNC SEVER STARTED ON PORT :1"
		echo "Connect it!!! Example :- ipaddress:1 in VNC Viewer"
		break
		;;
	3)
		echo "Bye Bye"
		break
		;;
 esac
done
